version: v2
budget: ai2/reviz # we were authorized to use this budget, but it may change
description: AI1/DDP Demo # user defined
tasks:
  - name: AI1.DDP
    replicas: 2
    leaderSelection: true
    hostNetworking: true
    propagateFailure: true
    propagatePreemption: true
    image:
      docker: cattledog/octo-test-pub
    result:
      path: /outputs
    resources:
      gpuCount: 2 # if you need more than 1 gpu you will need to change

    context:
      priority: normal
      preemptible: true
    constraints:
      cluster: [ ai2/ai1-aws-g6 ] # change the cluster to the one you want to use (differences in gpu, preemption, etc)
